require 'fileutils'
require 'erb'
require 'find'

require_relative 'plugin_info'
require_relative 'plugin_generator'
require_relative 'plugin_generator_ui'
require_relative 'plugin_info_collector'
require_relative 'plugin_manager'
require_relative 'plugin_search'
require_relative 'plugin_fetcher'
require_relative 'plugin_update_manager'
