# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MissingUrlSchemesApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MissingUrlSchemesApp
  pod 'Firebase/Auth'
  pod 'Firebase/DynamicLinks'
end
