// Plugins.swift
// Copyright (c) 2022 FastlaneTools

// This autogenerated file will be overwritten or replaced when installing/updating plugins or running "fastlane generate_swift"
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

import Foundation

// Please don't remove the lines below
// They are used to detect outdated files
// FastlaneRunnerAPIVersion [0.9.56]
