// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `scan`
class Scanfile: ScanfileProtocol {
// If you want to enable `scan`, run `fastlane scan init`
// After, this file will be replaced with a custom implementation that contains values you supplied
// during the `init` process, and you won't see this message
}





// Generated with fastlane 2.68.1