describe Fastlane do
  describe Fastlane::FastFile do
    describe "pilot Integration" do
      it "can use a generated changelog as release notes" do
        values = Fastlane::FastFile.new.parse("lane :test do
          # changelog_from_git_commits sets this lane context variable
          Actions.lane_context[SharedValues::FL_CHANGELOG] = 'autogenerated changelog'
          pilot
        end").runner.execute(:test)

        expect(values[:changelog]).to eq('autogenerated changelog')
      end

      it "prefers an explicitly specified changelog value" do
        values = Fastlane::FastFile.new.parse("lane :test do
          # changelog_from_git_commits sets this lane context variable
          Actions.lane_context[SharedValues::FL_CHANGELOG] = 'autogenerated changelog'
          pilot(changelog: 'custom changelog')
        end").runner.execute(:test)

        expect(values[:changelog]).to eq('custom changelog')
      end

      it "defaults distribute_only to false" do
        values = Fastlane::FastFile.new.parse("lane :test do
          pilot
        end").runner.execute(:test)

        expect(values[:distribute_only]).to eq(false)
      end

      it "allows setting of distribute_only to true" do
        values = Fastlane::FastFile.new.parse("lane :test do
          pilot(distribute_only: true)
        end").runner.execute(:test)

        expect(values[:distribute_only]).to eq(true)
      end

      describe "choosing the binary" do
        around do |example|
          Dir.mktmpdir do |dir|
            Dir.chdir(dir) do
              FileUtils.touch("stale.ipa")
              FileUtils.mkdir_p("build")
              FileUtils.touch("build/App.ipa")
              FileUtils.touch("build/App.pkg")
              example.run
            end
          end
        end

        def run_lane(params = "")
          Fastlane::FastFile.new.parse("lane :test do
            upload_to_testflight(#{params})
          end").runner.execute(:test)
        end

        it "uploads the ipa gym built, not the newest ipa in the current directory" do
          Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::IPA_OUTPUT_PATH] = File.expand_path("build/App.ipa")

          expect(File.expand_path(run_lane[:ipa])).to eq(File.expand_path("build/App.ipa"))
        end

        it "uploads an ipa given explicitly over the one gym built" do
          Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::IPA_OUTPUT_PATH] = File.expand_path("build/App.ipa")

          expect(File.expand_path(run_lane("ipa: 'stale.ipa'")[:ipa])).to eq(File.expand_path("stale.ipa"))
        end

        it "does not add an ipa from an earlier build when a pkg is given" do
          FileUtils.rm("stale.ipa")
          Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::IPA_OUTPUT_PATH] = File.expand_path("build/App.ipa")

          values = run_lane("pkg: 'build/App.pkg'")

          expect(values[:ipa]).to be_nil
          expect(File.expand_path(values[:pkg])).to eq(File.expand_path("build/App.pkg"))
        end
      end

      describe "Test `apple_id` parameter" do
        it "raises an error if `apple_id` is set to email address" do
          expect do
            options = {
              username: "username@example.com",
              apple_id: "username@example.com"
            }
            pilot_config = FastlaneCore::Configuration.create(Pilot::Options.available_options, options)
          end.to raise_error("`apple_id` value is incorrect. The correct value should be taken from Apple ID property in the App Information section in App Store Connect.")
        end

        it "raises an error if `apple_id` is set to bundle identifier" do
          expect do
            options = {
              username: "username@example.com",
              apple_id: "com.bundle.identifier"
            }
            pilot_config = FastlaneCore::Configuration.create(Pilot::Options.available_options, options)
          end.to raise_error("`apple_id` value is incorrect. The correct value should be taken from Apple ID property in the App Information section in App Store Connect.")
        end

        it "passes when `apple_id` is correct" do
          options = {
            username: "username@example.com",
            apple_id: "123456789"
          }
          pilot_config = FastlaneCore::Configuration.create(Pilot::Options.available_options, options)
          expect(pilot_config[:apple_id]).to eq('123456789')
        end
      end
    end
  end
end
