require 'frameit/frame_downloader'
require 'frameit/device_types' # color + orientation
require 'frameit/runner'
require 'frameit/screenshot'
require 'frameit/frame'
require 'frameit/config_parser'
require 'frameit/offsets'
require 'frameit/framer'
require 'frameit/template_finder'
require 'frameit/dependency_checker'
require 'frameit/options'
require 'frameit/wrapper/wrapper'
require 'frameit/wrapper/mac_wrapper'
require 'frameit/wrapper/trim_box'
require 'frameit/wrapper/strings_parser'
