require "bundler/gem_tasks"
require "rubocop/rake_task"
require "rspec"
require "rspec/core/rake_task"

Dir.glob('tasks/**/*.rake').each(&method(:import))

task :push do
  sh "../fastlane/bin/fastlane release"
end
