# Fetch and use the latest Fastfile from the fastlane main repository
import_from_git(url: "https://github.com/fastlane/fastlane/")

lane :deploy_aar do
  gradle(task: "clean screengrab-lib:assembleRelease bintrayUpload -PdryRun=false")
end