require 'bundler/gem_tasks'
require 'rubocop/rake_task'

Dir.glob('tasks/**/*.rake').each(&method(:import))

desc 'Release fastlane to the world!'
task :push do
  sh "../fastlane/bin/fastlane release"
end

task :generate_plugins do
  require 'fastlane/plugins/plugin_fetcher'
  Fastlane::PluginFetcher.update_md_file!
end

task :generate_docs do
  require 'fastlane/documentation/markdown_docs_generator'
  Fastlane::MarkdownDocsGenerator.new.generate!
end
