require 'bundler/gem_tasks'
require 'rubocop/rake_task'

Dir.glob('tasks/**/*.rake').each(&method(:import))

desc 'Release fastlane to the world!'
task :push do
  sh "../fastlane/bin/fastlane release"
end
