lane :snappy do |options|
  snapshot(
    project: 'Example.xcodeproj',
    scheme: 'ExampleUITests',
    devices: ['iPhone 6s', 'iPad Air'],
    output_simulator_logs: true,
    clear_previous_screenshots: true
  )
end
