# frozen_string_literal: true

task(default: %w[setup])

task(setup: [:brew, :lint])

task(:brew) do
  raise '`brew` is required. Please install brew. https://brew.sh/' unless system('which brew')

  puts('➡️  Brew')
  sh('brew bundle')
end

task(:lint) do
  Dir.chdir('../../../Sources/Fastlane') do
    sh("swiftformat . --verbose --selfrequired waitWithPolling --exclude Fastfile.swift")
  end
end
