# Fetch and use the latest Fastfile from the fastlane main repository
import("../../fastlane/Fastfile")

lane(:deploy_aar) do
  ensure_git_branch
  ensure_git_status_clean

  gradle(task: [
    'screengrab-lib:clean',
    'screengrab-lib:assembleRelease',
    'screengrab-lib:bintrayUpload',
    '-PdryRun=false'
  ].join(' '))
end
