# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoodApp
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
end
