---
name: Deploy to RubyGems
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy-to-rubygems:
    name: Deploy to RubyGems
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2'
      - uses: rubygems/release-gem@v1