---
name: Process issues
on:
  issues:
    types:
      - opened
permissions:
  issues: write

jobs:
  fastlane-env:
    name: Remind user about posting their fastlane env
    runs-on: ubuntu-latest
    steps:
      - uses: fastlane/github-actions/fastlane-env-reminder@9d169551c320140defc7894ca86e328b995831d8 # v0.7.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
