---
name: Process issues
on:
  issues:
    types:
      - opened
permissions:
  issues: write

jobs:
  fastlane-env:
    name: Remind user about posting their fastlane env
    runs-on: ubuntu-latest
    steps:
      - uses: fastlane/github-actions/fastlane-env-reminder@212cacd2e482bf799ecfe99e379b65b0f3eeba56 # v0.8.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
