name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened
      - synchronize # Add labels when PR receives new commits, which may modify the files in the PR
      - reopened

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
