name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened
      - synchronize # Add labels when PR receives new commits, which may modify the files in the PR
      - reopened

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
