---
name: Release Step 2 - Create GitHub Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      skip_github_packages:
        description: 'Skip pushing to GitHub Packages'
        required: true
        default: false
        type: boolean
      skip_rubygems:
        description: 'Skip pushing to RubyGems'
        required: true
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  create_github_release:
    runs-on: macos-latest

    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
      with:
        ruby-version: '3.4'

    - name: Install fastlane
      run: bundle install

    - uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0

    - name: Configure GitHub Packages config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.gem
        echo ":github: Bearer $GITHUB_TOKEN" > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials

    - name: Run fastlane
      env:
        FASTLANE_RELEASE_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane create_github_release skip_github_packages:${{ github.event.inputs.skip_github_packages }} skip_rubygems:${{ github.event.inputs.skip_rubygems }}

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: release_tag
        path: latest_fl_version.txt
        retention-days: 1
