source('https://rubygems.org')

gemspec

gem 'bundler'
gem 'fastlane', '>= <%= Fastlane::VERSION %>'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rubocop', '<%= Fastlane::RUBOCOP_REQUIREMENT %>'
gem 'rubocop-performance'
gem 'rubocop-require_tools'
gem 'simplecov'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
